In [4]:
print("Hello NumPy")

Hello NumPy


In [5]:
2+8*5

42

### This is just basic text.
this is a markdown

02_01 Array Types and conversions between types

In [6]:
import numpy as np

In [7]:
integers=np.array([10,20,30,40,50])

In [9]:
print(integers)

[10 20 30 40 50]


In [11]:
integers[0]

10

In [13]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [16]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [17]:
integers.dtype

dtype('int32')

In [19]:
smallerIntegers=np.array(integers, dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [20]:
integers.nbytes

20

In [21]:
smallerIntegers.nbytes

5

In [23]:
overflow = np.array([127,128,129], dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [25]:
floats=np.array([1.2,2.3,3.4,4.5,5.1,8.3])
print(floats)

[1.2 2.3 3.4 4.5 5.1 8.3]


In [26]:
floats.dtype

dtype('float64')

02_02 Multidementional arrays

In [29]:
import numpy as np


In [30]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
nums[0,0]

1

In [32]:
nums[1,4]

10

In [33]:
nums.ndim

2

In [37]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
multi_arr[1,0,2]

9

02_03
Creating array from lists and other python structures

In [39]:
import numpy as no

In [40]:
first_list= [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [41]:
first_array= np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
second_list = [1,2,3,-1.23,50,128000.56,4.56]

In [45]:
second_array = np.array(second_list)
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [46]:
second_array.dtype

dtype('float64')

In [48]:
third_list=['Ann', 111111,'Peter',11112,'Susan',11113,'John',11114]

In [51]:
third_array=np.array(third_list)
third_array

array(['Ann', '111111', 'Peter', '11112', 'Susan', '11113', 'John',
       '11114'], dtype='<U11')

In [53]:
first_tuple=(5,10,15,20,25,30)

In [54]:
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [55]:
array_from_tuple.dtype

dtype('int32')

In [56]:
multi_dim_list=[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]

In [58]:
arr_from_multi_dim_list = np.array(multi_dim_list)
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])